(lang dune 2.0)
(name minifun)

(using menhir 2.0)

(package
 (name minifun)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune ocamllex menhir ppx_deriving) 
 (tags
  (topics "to describe" your project)))